set BOOST_ROOT=%PREFIX%
set ZLIB_ROOT=%PREFIX%
set OPENSSL_ROOT=%PREFIX%
set OPENSSL_ROOT_DIR=%PREFIX%

set "CXXFLAGS=%CXXFLAGS% -DNOMINMAX"

cmake -B build -GNinja -S "%SRC_DIR%"^
      -DCMAKE_BUILD_TYPE=Release ^
      -DBIN_INSTALL_DIR="%LIBRARY_BIN%" ^
      -DLIB_INSTALL_DIR="%LIBRARY_LIB%" ^
      -DOpenSSL_ROOT="%LIBRARY_PREFIX%" ^
      -DOPENSSL_ROOT_DIR="%LIBRARY_PREFIX%" ^
      -DLIBEVENT_ROOT="%LIBRARY_PREFIX%" ^
      -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
      -DBUILD_PYTHON=OFF ^
      -DBUILD_JAVA=OFF ^
      -DBUILD_JAVASCRIPT=OFF ^
      -DBUILD_NODEJS=OFF ^
      -DBUILD_C_GLIB=OFF ^
      -DTHRIFT_COMPILER_NETSTD=OFF ^
      -DBoost_ADDITIONAL_VERSIONS="1.70.0" ^
      -DBOOST_ROOT=%LIBRARY_PREFIX% ^
      -DBoost_INCLUDE_DIRS=%LIBRARY_PREFIX%\include ^
      -DBoost_DEBUG=ON ^
      -DBoost_NO_BOOST_CMAKE=ON ^
      -DBUILD_TESTING=OFF ^
      -DBUILD_SHARED_LIBS=ON
if errorlevel 1 exit 1

cmake --build build
if errorlevel 1 exit 1
