{% set name = "thrift" %}
{% set version = "0.22.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://archive.apache.org/dist/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: 794a0e455787960d9f27ab92c38e34da27e8deeda7a5db0e59dc64a00df8a1e5
    patches:
      - patches/0003-Thrift-itself-needs-GlobalOutput.patch          # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("libthrift", max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja-base
    - msys2-bison        # [win]
    - msys2-flex         # [win]
    - bison           # [unix]
    - flex            # [unix]
    - pkg-config      # [unix]
  host:
    - libboost-headers {{ libboost }}
    - libevent {{ libevent }}  # [unix]
    - openssl {{ openssl }}
    - zlib {{ zlib }}

outputs:
  - name: libthrift
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x") }}
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja-base
        - msys2-bison        # [win]
        - msys2-flex         # [win]
        - bison           # [unix]
        - flex            # [unix]
        - pkg-config      # [unix]
      host:
        - libboost-headers {{ libboost }}
        - libevent {{ libevent }}  # [unix]
        - openssl {{ openssl }}
        - zlib {{ zlib }}
      run:
        - zlib
        - openssl  # exact pin handled through openssl run_exports
        - libevent # [unix]
    test:
      commands:
        - test ! -f $PREFIX/bin/thrift                                      # [unix]
        - test -f $PREFIX/lib/libthrift${SHLIB_EXT}                         # [unix]
        - test -f $PREFIX/include/thrift/Thrift.h                           # [unix]
        - if not exist %PREFIX%\\Library\\include\\thrift\\Thrift.h exit 1  # [win]
        - if exist %PREFIX%\\Library\\bin\\thrift.exe exit 1                # [win]
        - if not exist %PREFIX%\\Library\\lib\\thriftmd.lib exit 1          # [win]
  - name: thrift-compiler
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x") }}
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja-base
        - msys2-bison        # [win]
        - msys2-flex         # [win]
        - bison           # [unix]
        - flex            # [unix]
        - pkg-config      # [unix]
      host:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - libboost-headers {{ libboost }}
        - libevent {{ libevent }}  # [unix]
        - openssl {{ openssl }}
        - zlib {{ zlib }}
      run:
        - {{ pin_subpackage("libthrift", exact=true) }}
    test:
      commands:
        - test -f $PREFIX/bin/thrift                              # [unix]
        - if not exist %PREFIX%\\Library\\bin\\thrift.exe exit 1  # [win]
  - name: thrift-cpp
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x") }}
    requirements:
      host:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
        - {{ pin_subpackage("thrift-compiler", max_pin="x.x.x") }}
      run:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
        - {{ pin_subpackage("thrift-compiler", max_pin="x.x.x") }}

about:
  home: https://thrift.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Compiler and C++ libraries and headers for the Apache Thrift RPC system
  description: |
    Compiler and C++ libraries and headers for the Apache Thrift RPC system
  doc_url: https://thrift.apache.org/docs
  dev_url: https://github.com/apache/thrift

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
