# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PKXtb//LuRg6pB3TUDMRKiW5/BWlaMmtHV48IqoGXPlu5xFFLsY3Kua3Eciwc2I/lHzrGblCMP6OlApzuojVR63vrXuSyzzxZ6iXQMaUn8yRG5d4bgK6tKBk6xwLmucwqCLX9WBtFfLbEq/VKTAnndXTqQ0lcaU9jXUCwmOut5OoLvz8rEQ+tfD5oDQku8lxHpfNsP81M/jW7RIJT+ECFBXg2syKPkkFd4IucDlTZOVYW1SC8If/zRqTpRV4O5N5N6c9Oa630+ejry9hYCHY5sFmUJqTGbfiBrZvwTaBZd0Dmjsr9FTQ0w6MPtucibreeLctfaOlAbN3rrG3zbHRpxRvJG3FFAHp3QG6X8FCNUxmOr+o8Nn//LD80zgIZ/w82R3nAOAkcdtYf5aDmVxqb8LkV8xdMTMEET9vZkarH7J/6KbED861VRnnDxAiUJ3Zsa0aIJ4VcqIU2viNKQEVzlJOVjshXbangMH3y5LaUnSwBMlrLhv9dlAxdrc9dymrs63AVp+EX2mAzGQjD/JdzWll3KGJqHJBMhHNfc+6TSN2ZYlmaSTogrHmKnGuNgVvJkudBvK1PqIbcR4AUQawXlncCSTmMzEC3e6z/BQ7uGWwtoGZhIkWZaxnTksZv1VJgrqjP2YApk2Wt2n/BDSC0NSr5TMU3xyBQvZzMtAUQgk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
