travis:
  secure:
    BINSTAR_TOKEN: PKXtb//LuRg6pB3TUDMRKiW5/BWlaMmtHV48IqoGXPlu5xFFLsY3Kua3Eciwc2I/lHzrGblCMP6OlApzuojVR63vrXuSyzzxZ6iXQMaUn8yRG5d4bgK6tKBk6xwLmucwqCLX9WBtFfLbEq/VKTAnndXTqQ0lcaU9jXUCwmOut5OoLvz8rEQ+tfD5oDQku8lxHpfNsP81M/jW7RIJT+ECFBXg2syKPkkFd4IucDlTZOVYW1SC8If/zRqTpRV4O5N5N6c9Oa630+ejry9hYCHY5sFmUJqTGbfiBrZvwTaBZd0Dmjsr9FTQ0w6MPtucibreeLctfaOlAbN3rrG3zbHRpxRvJG3FFAHp3QG6X8FCNUxmOr+o8Nn//LD80zgIZ/w82R3nAOAkcdtYf5aDmVxqb8LkV8xdMTMEET9vZkarH7J/6KbED861VRnnDxAiUJ3Zsa0aIJ4VcqIU2viNKQEVzlJOVjshXbangMH3y5LaUnSwBMlrLhv9dlAxdrc9dymrs63AVp+EX2mAzGQjD/JdzWll3KGJqHJBMhHNfc+6TSN2ZYlmaSTogrHmKnGuNgVvJkudBvK1PqIbcR4AUQawXlncCSTmMzEC3e6z/BQ7uGWwtoGZhIkWZaxnTksZv1VJgrqjP2YApk2Wt2n/BDSC0NSr5TMU3xyBQvZzMtAUQgk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
