travis:
  secure:
    BINSTAR_TOKEN: haZZ/dC+kpXCkF83hzLYklZTHldipuQLEhuZ9mhkdgyJiKIe/EY6jVgA4eU/C5QYop8ZAWHPyoictkh3L/Qvzz/UV+pWudhPf+2jaPoGiXg6tQ61ENgzDTU+ksipK0ZFWSpAcgjJjJU335G/C6CHT1j7Kyzga25uXf1/kK4hg2e9TdISUxRCwjRAkVhivxDSnBQYItuqM/ChIiThZpzEl39lQEMT0XGNq+RXsrtERMDH/4B5aSvaMf4qFAPAGlGCjdyuCudHS1LaMoMbQRRlzGcf7myQnTmZQYsnqNNMpsKm8tHU8xyf3MH8zJvQhwSxGPdXE/TYAcbDkncq6OauDOiZ3K/pJMIiXkuDPsVIVB7xto6CGGjjkrVVmLiJt0mdZal5UrhZyUYB1UDyif3Nk6++SZdEFUgIS2zF2b/Ns9qjqnOM2Ka4az3rqh6/aqoe6/UkGYniSffBzCiqpK6y9DPG67aCtbWS+sywhsWK307EDwlwHBSTb32XpJK3m3UoqainkScY8JdMdEccyZNfm0xrUXSN+WjEVhkx5OJkwMt7VvVIvLiIdd5BbM5bBp55zuCX7g1MC2vcVElmDR68kJ21AhwggjxHBIRspCrZOra4UWejc+ceKh3Nh6HACeMwWBtQ0dcQ5q9LU/Move2PgKOytDtXk3UWeCsmEwKSRwM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
