travis:
  secure:
    BINSTAR_TOKEN: HpmHpWLLvwukGHe9xB6pNREb674I6CWr3i47VNImdWc9Xx9heNtoxjAp4io/CdVyMcuSppmZF4IrJeJVqXaGlaWi6pBrFTDh4GNgSQC8UE8GD/SmFWW0qViWcuk9IDkYrKRya7OVl9eWq/mUYz9TORXQjcyu6E12IXao0rYtXC2Z4DPIcqcU1el6WimIQ+JHpYM6etHXtayZdl8iKwgdzb1YM+c5uvZxTDkhhRooe6r33Kt0Id6q6+NBeTC4138/zQB3C1sbTacM0XTPWARyApNn8D7XXnhifuSrcdYSINZnMWmwZvdbYDxClc5Qpv/yoH1S/B/DF9R0omVu6fQMig6sPswT4JB79uleVwOVdrmhMNNhjDioKss2FeIEqbj5NG2mUAgx7DQj29SYPoAxMPrOuyIihMnzcRfIraFFRuUdjDKzgIOtK0bDWclm/gKggs+mbYJEGQrzDJbbFslFN0NaDkcYhXhRtdo7o4e00BEK4AlDB7FroPi2pkePPG+xHlcgeQyoHIoJRX+I6eyG5Ls++jTePMWn9PcCS7o+r2A7CmL7ht8Y/+8bJ1z0/GSf6YLBQYPH8ACXjdr2LbpYPxwn4tXiPgSsTnv8G1J5uOeLdkv3cEEjPX/783ObqglDWpYsVZkPVIvZPoYGTEXB+zBlGpYopzuSA1FGJa7rjIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
